config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :friends
  #root "home#index"
  root "friends#index"
  get "home/about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /friends or /friends.json
  def index
    if user_signed_in?
      @friends = current_user.friends
    else
      @friends = Friend.all
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end

    def correct_user
      @friend = current_user.friends.find_by(params[:id]) 
      redirect_to friends_path, notice: "U are not authorized for this action." if @friend.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_2_helper.rb
module Home2Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>


  <div class="form-group">
    <%= form.number_field :user_id, class:"form-control", id: :friend_user_id, value: current_user.id, hidden:true%>
  </div>

  <br/>
  <div>
    <%= form.submit nil, :class =>"btn btn-secondary"%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <div class="jumbotron">
    <h1 class="display-4"><%= friend.first_name %> <%= friend.last_name %></h1>
    <br/>
    <p class="lead"><%= friend.email %>|<%= friend.phone %>|<%= friend.twitter %></p>
  </div>
</div>
<br/>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend , class:"btn btn-secondary"%> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
  <% if user_signed_in?%>
  
  <h1>Friend List</h1>

  <table class="table table-striped table-hover table-borderless">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Twitter</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend|%>
        <tr class="align-bottom">   
          <td>
          <%= link_to friend.first_name + ' ' +friend.last_name ,friend_path(friend)%> 
          </td>
          <td> <%= friend.phone %> </td>
          <td> <%= friend.email %> </td>
          <td> <%= friend.twitter %> </td>

          <%#destroy link_to button_to%>
          <td> <%= button_to "Delete",friend, method: :delete, class:"btn btn-outline-danger"%> </td>
        </tr> 
      <%end%>
    </tbody>
  </table>


  <%=link_to "New Friend",new_friend_path,class:"btn btn-secondary"%>

<% else%>
  <h1 style="color:green;">Orj Home Page</h1>
  <p>Find me in app/views/home/index.html.erb</p>
<% end%>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path , class:"btn btn-dark"%>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div class="d-flex">
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary me-3"%>
  <%= button_to "Delete",@friend, method: :delete, class:"btn btn-danger me-3"%>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App",root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Friends",friends_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Add Friend",new_friend_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out",destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile",edit_user_registration_path, class:"nav-link"%>
          </li>
        <% else%>
          <li class="nav-item">
            <%= link_to "Sign In",new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up",new_user_registration_path, class:"nav-link"%>
          </li>
        <%end%>
       

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1 style="color:green;">Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%=notice%></strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header"%>

    <%if notice%>
      <%= render "layouts/alert"%>
    <%end%>
    <div class="container-lg">
        <%= yield%>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>